Fixed pull_all

diff --git a/cli/install b/cli/install
--- a/cli/install
+++ b/cli/install
@@ -3,6 +3,15 @@
 cd $(dirname $0)
 
 pyinstaller --onefile --icon=icon.ico --name=phitnest src/phitnest.py
+
+# Check the exit status of the pyinstaller command
+if [ $? -ne 0 ]; then
+    echo "============================================="
+    echo " F A I L E D   T O   I N S T A L L "
+    echo "============================================="
+    exit 1
+fi
+
 echo "============================================="
 echo " S U C C E S S F U L L Y   I N S T A L L E D "
 echo "============================================="
